### ISSUE TITLE
Error when running on nightly, invalid arguments reported when no arguments are supplied

### ISSUE THREAD

**Issue by PhilipDaniels** [sfackler/cargo-tree#36]
On nightly:

```
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.26.0-nightly (75af15ee6 2018-03-20)
```

Installed cargo-tree ok. When running:

```
$ cargo tree
error: Invalid arguments.

Usage: cargo tree [options]
```

The same thing happens with `cargo-outdated`, so this might be a problem/change in cargo itself that is now showing itself here. However, `cargo clippy` works fine.

Should say that the same thing happens with a direct run of `cargo-tree`.

**Comment by PhilipDaniels** [comment]
Can also confirm that switching to stable, it works fine.

**Comment by sfackler** [comment]
Cargo invokes subcommands with the first argument being its name, so you need to run `cargo-tree tree <ARGS>` to run it directly. It seems to work just fine for me running `cargo +nightly tree` though. There was a bug in Cargo recently that broke subcommands but I think it's fixed in the current nightly.

**Comment by PhilipDaniels** [comment]
Ah, I rebuilt my PC this week and it seems I hit that bug. I updated to latest nightly and it works again now. Sorry to waste your time, closing issue.
