### ISSUE TITLE
migrate to cargo?

### ISSUE THREAD

**Issue by ehuss** [sfackler/cargo-tree#96]
A few people of expressed that they would like `cargo tree` installed by default with Cargo. I was wondering what your thoughts are about moving cargo-tree into rust-lang/cargo? I (or someone else) would be willing to do the work, so this is mostly a question of whether or not you would be OK with that. I realize that cargo-tree was just rewritten, and I feel bad about the timing asking this. 

cc @joshtriplett @alexcrichton @eh2406

**Comment by sfackler** [comment]
That'd be awesome! No worries about asking after the rewrite - the old version probably needed to be burned down and rewritten anyway.

**Comment by joshtriplett** [comment]
@sfackler Glad to hear that!

A version integrated into Cargo will probably want to go back to linking to Cargo and using the Cargo dependency graph directly, rather than just calling `cargo metadata`. Do you think it makes more sense to do that by grabbing the pre-rewrite version of cargo-tree and updating it, or taking the rewritten version and porting it "back" to use cargo directly rather than cargo-metadata?

**Comment by sfackler** [comment]
I'm not sure - the old version was definitely incorrect in a couple of ways. In particular it failed to account for `[patch]` and crate renames IIRC. Someone more familiar with Cargo's internals could probably work off of the old codebase and fix it up, but I don't know how extensive the fix would need to be.

**Comment by ehuss** [comment]
Thanks @sfackler!  I'll take a look sometime soon, I don't expect it to be too difficult.

**Comment by ehuss** [comment]
`cargo tree` is now available on nightly, so I think this can be closed.  Thanks @sfackler!
